swagger: "2.0"
info:
  version: "0.0.1"
  title: Labs Api Native Parser Parking Lot
# during dev, should point to your local machine
host: labs-api-nppl-prod-webbapp.azurewebsites.net
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /getParking:
    # binds a127 app logic to a route
    x-swagger-router-controller: parkingLots
    get:
      description: Returns a array of parkings in a distance radius from specified point
      # used as the method name of the controller
      operationId: parkingLots
      parameters:
        - name: lat
          in: query
          description: latitude
          required: true
          type: string
        - name: lon
          in: query
          description: Longitude
          required: true
          type: string
        - name: dist
          in: query
          description: Distance
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/GetParkingResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  GetParkingResponse:
      type: "array"
      items:
        $ref: "#/definitions/Parking"
  Parking:
    type: "object"
    properties:
      name:
        type: "string"
      lat:
        type: "number"
      lon:
        type: "number"
      dist:
        type: "string"
